name: Documentation
on: push

concurrency: ci-${{ github.ref }}

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/build
      - name: Pre-compile TOC
        run: pnpm predocs

      - name: Build vuepress docs
        run: pnpm docs:build

      # Build all examples (except for docgen-nuxt which needs to be sent to surge)
      - name: Build examples
        run: cd examples; for D in *; do if [ $D != "docgen-nuxt" ]; then cd ..; pnpm build "${D}" -- --ci; cd examples; fi; done || exit 1

      # Move them to the docs (except for docgen-nuxt which needs to be sent to surge)
      - name: Move examples to docs
        run: for D in *; do if [ $D != "docgen-nuxt" ]; then mv "${D}"/dist ../docs/dist/"${D}"; fi; done || exit 1
  
  deploy: 
    needs: build-docs
    runs-on: ubuntu-latest

    steps:
      - run: echo "Deploying docs to gh-pages..."