name: Deliver a release
on:
  push:
    branches:
      - deliver

concurrency: 
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    # to be changed to branch delivery when final merge is done
    uses: vue-styleguidist/vue-styleguidist/.github/workflows/test.yml@build/gh-actions

  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/build
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}