name: Release Next
on:
  push:
    branches:
      - next

concurrency:
  group: release-next-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: vue-styleguidist/vue-styleguidist/.github/workflows/test.yml@next

  release-beta:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Init & Build
        uses: ./.github/actions/build

      - name: Setup GitHub User
        run: |
          git config --global user.name "Vue Styleguidist Bot"
          git config --global user.email "${{ secrets.BOT_EMAIL }}"

      - run: npx --yes --package=lerna -- lerna version --yes --create-release=github --conventional-prerelease --preid beta
      - run: npx --yes --package=lerna -- lerna publish from-git --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}