name: Deliver a release
on:
  push:
    branches:
      - deliver
jobs:
  call-build:
    # to be changed to branch delivery when final merge is done
    uses: vue-styleguidist/vue-styleguidist/.github/workflows/build.yml@build/gh-actions

  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/build
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}